server.tomcat.max-threads=8
simulador.debug.retornar-request=true
simulador.max-requests-externos=1

server.servlet.contextPath=/financiamentos

spring.main.lazy-initialization=true
server.port=8080
#management.server.port=8081
info.app.version=@project.version@ @maven.build.timestamp@

spring.redis.host=redis
spring.redis.port=6379
spring.redis.password=changeme
spring.redis.timeout=0

spring.data.rest.default-media-type=application/json
spring.mvc.locale=pt_BR
server.compression.enabled=true
server.compression.mime-types=application/json
server.compression.min-response-size=1024
spring.cache.redis.cache-null-values=true
server.http2.enabled=true
#spring.data.mongodb.uri=mongodb://mongoadm:changeme@mongodb-0.mongodb-internal.new-front-dev.svc.cluster.local:27017/btb
spring.data.mongodb.uri=mongodb://mongo:mongo@BTVND2DVMDB01.dev.corp.btb:27017/propostas?authSource=admin

spring.jackson.default-property-inclusion=NON_NULL
spring.jackson.deserialization.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT=true

logging.level.root=INFO
logging.level.access-log=INFO
logging.level.org.springframework=INFO
logging.level.br.com.bancotoyota.services.simulador.controller=info
logging.level.br.com.bancotoyota.services.simulador.services.LogService=debug
logging.level.org.apache.tomcat.util.threads.LimitLatch=debug
logging.level.br.com.bancotoyota.services.simulador.services.IntermediariasService=DEBUG
logging.level.br.com.bancotoyota.services.simulador.services.impl.RestaUmServiceImpl=DEBUG
logging.level.br.com.bancotoyota.services.simulador.controller.SimuladorParcDesejadaController=DEBUG

simulador.subsidio-minimo-por-valor=10

# porcentagem
simulador.desejada.max-diferenca=5

simulador.intermediaria.max-porcentual=8

# Tempo de espera antes de sair da JVM uma vez que o sinal para terminar e recebido
# Tem que ser maior que o periodSeconds do readiness probe do OpenShift para que da tempo do OpenShift parar de enviar
# requests e tambem de terminar os ultimos requests recebidos.
estaGracefulShutdownWaitSeconds=1

#gateway=http://app-new-front-dev.containers.sistemas.devbtb/api
#gateway=https://directhml.bctoyota.com.br/api
gateway=https://sandboxapidev.bancotoyota.com.br
api.seguro.garantia.url=${gateway}/seguros/v2/garantia
api.clientes.url=${gateway}/clientes/v3
ambiente=dev.apps.dev
ambiente-openshift=dev.apps.dev

# Request RITM0012247
#api.emplacamentos.url=http://10.200.102.80:8101/emplacamentos
#api.emplacamentos.url=https://api.bancotoyota.com.br/emplacamentos/v1
api.emplacamentos.url=http://api-emplacamento-new-front-${ambiente}.corp.btb/emplacamentos
#api.origens-negocios.url=http://10.200.102.80:8115/origens-negocios
#api.origens-negocios.url=https://api.bancotoyota.com.br/origens-negocios/v1
api.origens-negocios.url=http://api-origens-negocios-new-front-${ambiente}.corp.btb/origens-negocios
#api.cestas-servicos.url=http://10.200.102.80:8100/cestas-servicos
#api.cestas-servicos.url=https://api.bancotoyota.com.br/cestas-servicos/v1
api.cestas-servicos.url=http://api-cestaservicos-new-front-${ambiente}.corp.btb/cestas-servicos
#api.planos.url=http://10.200.102.80:8110/financiamentos/planos
#api.planos.url=http://api-financiamentos-plano-new-front-${ambiente}.apps.dev.cloud.corp/financiamentos/planos
#api.planos.url=http://api-planos-v2-new-front-homolog.corp.btb/financiamentos/planos
api.planos.url=http://api-motor-taxas-planos-new-front-${ambiente}.corp.btb/motor/taxas
#api.planos.url=http://api-planos-v2-new-front-dev.apps.dev.cloud.corp/financiamentos/planos
simulacao-simplificada-parceiros.enabled=true
api.veiculos.enabled=true
#api.veiculos.url=http://10.200.102.80:8117/veiculos
#api.veiculos.url=https://api.bancotoyota.com.br/veiculos/v1
api.veiculos.url=http://api-veiculos-new-front-${ambiente}.corp.btb/veiculos
#api.propostas-financiamento.url=https://sandboxapi.bancotoyota.com.br/financiamentos/propostas/v1
api.propostas-financiamento.url=http://api-financiamentos-propo-new-front-${ambiente}.corp.btb/financiamentos/propostas
#origens-solicitacao.gravar-simulacao-simplificada=ABRADIT,INSTITUCIONAL,LANDING_PAGE,CRED_FACIL_INSTITUCIONAL,CRED_INTELIGENTE_INSTITUCIONAL,TDB
mongodb.propostas.uri=mongodb://mongo:mongo@BTVND2DVMDB01.dev.corp.btb:27017/propostas?authSource=admin
mongodb.simulacoes-parceiros.uri=mongodb://user_parceiros:parceiros9802@BTVND2DVMDB01.dev.corp.btb:27017/simulacoes_parceiros?authSource=admin
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

api.motor-taxa.url=http://api-motor-taxas-planos-new-front-${ambiente}.corp.btb/motor/taxas

# usado pelo OBO
simulacao-simplificada.perfil.usuario=COORDENADOR

# ES - sao planos deste estado
# PCD - nao tem campo
planos.obo.filter=!(descricao.contains('PCD') or descricao.startsWith('ES') or descricao.contains('FLAT') or descricao.contains('IOF') or descricao.contains('S/P') or descricao.contains('TEST') or descricao.contains('FUNC') or descricao.contains('TCUV')  or descricao.contains('BLACK'))
planos.filter=!(descricao.contains('PCD') or descricao.startsWith('ES') or descricao.contains('FLAT') or descricao.contains('IOF') or descricao.contains('S/P') or descricao.contains('TEST') or descricao.contains('FUNC') or descricao.contains('TCUV')  or descricao.contains('BLACK'))

maven.build.timestamp=@maven.build.timestamp@

management.endpoints.web.path-mapping.health=readiness
management.endpoints.web.path-mapping.info=liveness
management.endpoints.web.exposure.include=health,info,env

simulacao-desejada-nova.enabled=true
planos.filtro-id-modalidade.enabled=true
spring.retry.numero-retentativas=5
spring.retry.delay-entre-retentativas-ms=1000

security.oauth2.service-url=${gateway}/
security.oauth2.token-url=${gateway}/oauth
#security.oauth2.username-parceiros=user_api_simulacao
#security.oauth2.password-parceiros=eO0L2#1@nKl1

#homolog direct
security.oauth2.username-parceiros=user_api_newfront
security.oauth2.password-parceiros=C##0o1zL2!

security.oauth2.grant-type=password

# dev
#security.oauth2.client-id=dea92fb2-39e0-4fac-9bb7-10b66f0c17c5
#security.oauth2.client-secret=a8273959-0c7a-46b9-afe6-2c0828a7076f
#security.oauth2.trust-store=gw-certs.jks
#security.oauth2.trust-store-password=changeme

#homolog
security.oauth2.client-id-parceiros=a34997bb-f7ed-4de2-b2f0-92222b096f37
security.oauth2.client-secret-parceiros=74589fbc-692f-4deb-ad80-fa57d48c1450

##homolog direct
#security.oauth2.client-id-parceiros=561719a4-2ebd-4d20-9b6f-ec586135212d
#security.oauth2.client-secret-parceiros=0e95fe39-258e-4553-949c-4e3a3055ca5e

seguro.prestamista.plus.url=https://sandboxapidev.bancotoyota.com.br/seguros/protecao/financeira/v1/taxas


simulador.consulta.seguro.prestamista.enabled=true
security.oauth2.direct-username=user_api_newfront
security.oauth2.direct-password=C##0o1zL2!
security.oauth2.direct-grant-type=password
security.oauth2.direct-client-id=50dfbe95-bf97-4ae9-bb6b-c929e410d0aa
security.oauth2.direct-client-secret=7df2c8da-2544-4b9f-b52c-5d8e556067a7


busca-api-motor-taxa.enabled=true
ciclo-intermediarias.enabled=true