server.tomcat.max-threads=8
simulador.max-requests-externos=0

# Tempo de espera antes de sair da JVM uma vez que o sinal para terminar é recebido
# Tem que ser maior que o periodSeconds do readiness probe do OpenShift para que dê tempo do OpenShift parar de enviar
# requests e também de terminar os últimos requests recebidos (somar o período do probe com o tempo máximo de execução).
estaGracefulShutdownWaitSeconds=1

spring.redis.host=172.17.0.1

logging.level.root=INFO
logging.level.access-log=INFO
logging.level.org.springframework=INFO
logging.level.br.com.bancotoyota.services.simulador.controller=info
logging.level.br.com.bancotoyota.services.simulador.services.LogService=debug
logging.level.org.apache.tomcat.util.threads.LimitLatch=debug

