server.tomcat.max-threads=8
simulador.debug.retornar-request=false
simulador.max-requests-externos=0


# Tempo de espera antes de sair da JVM uma vez que o sinal para terminar é recebido
# Tem que ser maior que o periodSeconds do readiness probe do OpenShift para que dê tempo do OpenShift parar de enviar
# requests e também de terminar os últimos requests recebidos (somar o período do probe com o tempo máximo de execução).
estaGracefulShutdownWaitSeconds=60

logging.level.access-log=INFO
