package br.com.bancotoyota.services.simulador.entities;

import lombok.AllArgsConstructor;
import lombok.Getter;
import  br.com.bancotoyota.services.simulador.common.Constants;
@Getter
@AllArgsConstructor
public enum EnumErroValidacao {
	ERRO_TIPO_SEGURO_PRESTAMISTA_INVALIDO("600",
			Constants.ERRO_TIPO_SEGURO_PRESTAMISTA_INVALIDO),
	ERRO_SEGURO_PRESTAMISTA_INVALIDO_SPF("601", Constants.ERRO_SEGURO_PRESTAMISTA_INVALIDO),
	ERRO_SEGURO_PRESTAMISTA_INVALIDO_SVP("602", Constants.ERRO_SEGURO_PRESTAMISTA_INVALIDO),
	ERRO_SEGURO_PRESTAMISTA_INVALIDO_NENHUM("603", Constants.ERRO_SEGURO_PRESTAMISTA_INVALIDO),
	ERRO_PLANO_SEM_SUBSIDIO_TAXA_MENSAL_INVALIDA("700",Constants.ERRO_PLANO_SEM_SUBSIDIO_TAXA_MENSAL_INVALIDA),
	ERRO_PLANO_SEM_SUBSIDIO_PLANO_NAO_ACEITA_SUBSIDIO("701",Constants.ERRO_PLANO_SEM_SUBSIDIO_PLANO_NAO_ACEITA_SUBSIDIO),
	ERRO_PLANO_NAO_ENCONTRADO("702",Constants.ERRO_PLANO_NAO_ENCONTRADO),
	ERRO_PERCENTUAL_RESIDUAL_SUPERIOR_LIMITE("703",Constants.ERRO_PERCENTUAL_RESIDUAL_SUPERIOR_LIMITE),
	ERRO_PERCENTUAL_RESIDUAL_INFERIOR_LIMITE("704",Constants.ERRO_PERCENTUAL_RESIDUAL_INFERIOR_LIMITE),
	ERRO_PLANO_COM_SUBSIDIO_SEM_TAXA("705",Constants.ERRO_PLANO_COM_SUBSIDIO_SEM_TAXA),
	ERRO_PLANO_COM_SUBSIDIO_TAXA_INVALIDA("706", Constants.ERRO_PLANO_COM_SUBSIDIO_TAXA_INVALIDA),
	ERRO_PLANO_COM_SUBSIDIO_TAXA_MINIMA_ERRADA("707",Constants.ERRO_PLANO_COM_SUBSIDIO_TAXA_MINIMA_ERRADA),
	ERRO_PLANO_COM_SUBSIDIO_TAXA_MAXIMA_EXCEDIDA("708",Constants.ERRO_PLANO_COM_SUBSIDIO_TAXA_MAXIMA_EXCEDIDA),
	ERRO_PLANO_COM_SUBSIDIO_TAXA_MES_IGUAL_TAXA_SUBSIDIO("709",Constants.ERRO_PLANO_COM_SUBSIDIO_TAXA_MES_IGUAL_TAXA_SUBSIDIO),
	ERRO_PLANO_NAO_PODE_SER_USADO_COM_DETERMINADA_QUANTIDADE_PARCELAS("710",Constants.ERRO_PLANO_NAO_PODE_SER_USADO_COM_DETERMINADA_QUANTIDADE_PARCELAS),
	ERRO_PERCENTUAL_ENTRADA_FORA_LIMITE_PLANO("711",Constants.ERRO_PERCENTUAL_ENTRADA_FORA_LIMITE_PLANO),
	ERRO_CAMPO_OBRIGATORIO("712", ""), //No enum ao lado será usado mensagens dinamicas
	ERRO_PERCENTUAL_BALAO_SUPERIOR_LIMITE("713",Constants.ERRO_PERCENTUAL_BALAO_SUPERIOR_LIMITE),
	ERRO_PERCENTUAL_BALAO_INFERIOR_LIMITE("714",Constants.ERRO_PERCENTUAL_BALAO_INFERIOR_LIMITE),
	ERRO_API_CLIENTES_INDISPONIVEL("715", Constants.ERRO_API_CLIENTES_INDISPONIVEL),
	ERRO_SUBSIDIO_FORA_FAIXA("716",""),
	ERRO_VALOR_ENTRADA_INTERMEDIARIAS_MAIOR_QUE_BEM("717","Valor da entrada muito alto. Entrada mais valor para a parcela residual/intermediárias não pode ser maior que o valor do bem."),

	ERRO_RESTRICOES_INTERMEDIARIAS("718","Erro na validação das restrições das intermediárias"),
	ERRO_VALOR_INVALIDO_INTERMEDIARIA("719","Valor da parcela intermediária está fora dos limites estabelecidos na tabela"),
	ERRO_SEGURO_MECANICA_INELEGIVEL("720", "As informações disponibilizadas não atendem os critérios de aceitação para o produto Garantia Mecânica.");
	private String key;
	private String value;
}
